"""Add item_data to recycle_bin

Revision ID: 16bc55123177
Revises: 912124213daa
Create Date: 2026-08-23 19:34:00.288661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16bc55123177'
down_revision: Union[str, Sequence[str], None] = '912124213daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recycle_bin', sa.Column('item_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recycle_bin', 'item_data')
    op.drop_index(op.f('ix_company_budgets_month'), table_name='company_budgets')
    op.drop_index(op.f('ix_company_budgets_id'), table_name='company_budgets')
    # ### end Alembic commands ###
