"""Add company_budgets table

Revision ID: 373bdf771987
Revises: 1f23b3b77908
Create Date: 2026-08-21 14:27:00.438223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '373bdf771987'
down_revision: Union[str, Sequence[str], None] = '1f23b3b77908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_budgets',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_budgets_id'), 'company_budgets', ['id'], unique=False)
    op.create_index(op.f('ix_company_budgets_month'), 'company_budgets', ['month'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_budgets_month'), table_name='company_budgets')
    op.drop_index(op.f('ix_company_budgets_id'), table_name='company_budgets')
    op.drop_table('company_budgets')
    # ### end Alembic commands ###
