"""Initial schema

Revision ID: 587dc7402407
Revises: 
Create Date: 2026-08-12 11:31:49.316527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '587dc7402407'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'revenue')
    op.add_column('projects', sa.Column('start_date', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('end_date', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'created_at')
    op.drop_column('projects', 'end_date')
    op.drop_column('projects', 'start_date')
    op.add_column('clients', sa.Column('revenue', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
