"""Add failed_login_attempts and is_blocked to User

Revision ID: 6de5a2d62d72
Revises: 16bc55123177
Create Date: 2026-08-23 19:46:37.304039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de5a2d62d72'
down_revision: Union[str, Sequence[str], None] = '16bc55123177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_company_budgets_id'), 'company_budgets', ['id'], unique=False)
    op.create_index(op.f('ix_company_budgets_month'), 'company_budgets', ['month'], unique=True)
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_blocked')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_index(op.f('ix_company_budgets_month'), table_name='company_budgets')
    op.drop_index(op.f('ix_company_budgets_id'), table_name='company_budgets')
    # ### end Alembic commands ###
